# Copyright (C) 2017 Tomoaki Kawada
#
# This file is part of tcwtecs.
#
# tcwtecs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tcwtecs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tcwtecs.  If not, see <http://www.gnu.org/licenses/>.

INCLUDES := -I$(TCWDIR)/include -I$(GENDIR) -I$(COMMONDIR) -I$(COMMONDIR)/$(TARGETNAME) -I.
INCLUDES_TECS := -I$(TCWDIR)/src -I$(SRCDIR) -I$(COMMONDIR) -I$(COMMONDIR)/$(TARGETNAME)

CFLAGS := $(CFLAGS) $(INCLUDES) "-DInline=static inline"
CXXFLAGS := $(CFLAGS) -std=c++1z

# make.inc defines the list of non-TECS object files as $(TCWTECS_OBJS)
include $(TCWDIR)/src/Makefile.tcw

# source file directories
vpath %.c $(TCWDIR)/src
vpath %.c $(GENDIR)
vpath %.c $(SRCDIR)
vpath %.c $(COMMONDIR)
vpath %.c $(COMMONDIR)/$(TARGETNAME)
vpath %.s $(COMMONDIR)/$(TARGETNAME)
vpath %.cpp $(TCWDIR)/src

# TECS interface code generation
tecs:
	$(TECSGEN) $(INCLUDES) $(INCLUDES_TECS) $(MAINCDL)

-include gen/Makefile.tecsgen

OBJS := $(OBJS) $(TCWTECS_OBJS) $(TECS_COBJS)

#
# Embedded bitmap images
#
IMAGEDIR := $(COMMONDIR)/images

MAKETCWIMAGE := $(TCWDIR)/tools/maketcwimage.rb

Image_Digits.c Image_Digits.h: $(IMAGEDIR)/Digits.png $(MAKETCWIMAGE)
	$(MAKETCWIMAGE) -i $(IMAGEDIR)/Digits.png -f mono -n Image_Digits -o Image_Digits

Image_StartStop.c Image_StartStop.h: $(IMAGEDIR)/StartStop.png $(MAKETCWIMAGE)
	$(MAKETCWIMAGE) -i $(IMAGEDIR)/StartStop.png -f mono -n Image_StartStop -o Image_StartStop

Image_Reset.c Image_Reset.h: $(IMAGEDIR)/Reset.png $(MAKETCWIMAGE)
	$(MAKETCWIMAGE) -i $(IMAGEDIR)/Reset.png -f mono -n Image_Reset -o Image_Reset
