# Copyright (C) 2017 Tomoaki Kawada
#
# This file is part of tcwtecs.
#
# tcwtecs is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tcwtecs is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tcwtecs.  If not, see <http://www.gnu.org/licenses/>.

TARGETNAME := grpeach

TECSGEN := tecsgen

CC = arm-none-eabi-gcc
CXX = arm-none-eabi-g++
LD = arm-none-eabi-g++
AR = arm-none-eabi-ar

CFLAGS := -mcpu=cortex-a9 -mthumb -mthumb-interwork -marm -march=armv7-a -mfpu=vfpv3 -mfloat-abi=hard -mno-unaligned-access
CFLAGS := $(CFLAGS) -ffunction-sections -fdata-sections -fno-builtin -funsigned-char -fomit-frame-pointer
CFLAGS := $(CFLAGS) -Os

default:        all
all:            $(TARGET)

.PHONY:	default all clean

include $(COMMONDIR)/Makefile.common

clean:
	rm -rf gen $(OBJS)

$(TARGET):      $(OBJS)
	rm -f $(TARGET)
	$(AR) rcs $(TARGET) $(OBJS)

