/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tBitmapSource_template.c => src/tBitmapSource.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * attr access macro #_CAAM_#
 * data             const char*      ATTR_data
 * dataSize         uint32_t         ATTR_dataSize
 * infoHeader       const TWBitmapInfoHeader*  ATTR_infoHeader
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tBitmapSource_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eImageData
 * entry port: eImageData
 * signature:  sBitmapData
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eImageData_get
 * name:         eImageData_get
 * global_name:  tBitmapSource_eImageData_get
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eImageData_get(CELLIDX idx, const char** data, uint32_t* numBytes, TWBitmapInfoHeader* infoHeader)
{
	CELLCB	*p_cellcb = GET_CELLCB(idx);
	*data = ATTR_data;
    *numBytes = ATTR_dataSize;
    *infoHeader = *ATTR_infoHeader;
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
