/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tDigitsViewCore_template.c => src/tDigitsViewCore.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cBoundsSource signature: sTWRectSource context:task
 *   void           cBoundsSource_get( TWRect* outRect );
 * call port: cDrawingContext signature: sTWDrawingContext context:task
 *   void           cDrawingContext_fillRect( TWColor color, const TWRect* rect );
 *   void           cDrawingContext_drawBitmap( const char* data, TWPixelFormat format, const TWSize* bitmapSize, uint32_t numBytes, const TWRect* inRect, const TWPoint* outLoc, TWColor monoColor );
 * call port: cViewControl signature: sTWViewControl context:task
 *   TWViewStyle    cViewControl_getStyle( );
 *   void           cViewControl_getBounds( TWRect* outRect );
 *   void           cViewControl_getGlobalBounds( TWRect* outRect );
 *   void           cViewControl_setNeedsUpdate( );
 * call port: cTextSource signature: sStringValueSource context:task
 *   void           cTextSource_get( char* outString, uint16_t bufferSize );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tDigitsViewCore_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# ePaintEvent
 * entry port: ePaintEvent
 * signature:  sTWPaintEvent
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# ePaintEvent_paint
 * name:         ePaintEvent_paint
 * global_name:  tDigitsViewCore_ePaintEvent_paint
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
ePaintEvent_paint(CELLIDX idx)
{
	CELLCB *p_cellcb = GET_CELLCB(idx);

	// TODO: ePaintEvent_paint
}

/* #[<ENTRY_PORT>]# eTextSource
 * entry port: eTextSource
 * signature:  sTWValueSourceCallback
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eTextSource_changing
 * name:         eTextSource_changing
 * global_name:  tDigitsViewCore_eTextSource_changing
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eTextSource_changing(CELLIDX idx)
{
}

/* #[<ENTRY_FUNC>]# eTextSource_changed
 * name:         eTextSource_changed
 * global_name:  tDigitsViewCore_eTextSource_changed
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eTextSource_changed(CELLIDX idx)
{
	CELLCB *p_cellcb = GET_CELLCB(idx);

	cViewControl_setNeedsUpdate();
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
