/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tStopwatchAppWindowCore_template.c => src/tStopwatchAppWindowCore.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cDC signature: sTWDrawingContext context:task
 *   void           cDC_fillRect( TWColor color, const TWRect* rect );
 *   void           cDC_drawBitmap( const char* data, uint32_t numBytes, const TWBitmapInfo* info, uint16_t infoSize, const TWRect* inRect, const TWPoint* outLoc );
 * call port: cStopwatch signature: sStopwatchControl context:task
 *   void           cStopwatch_start( );
 *   void           cStopwatch_stop( );
 *   void           cStopwatch_reset( );
 *   bool           cStopwatch_isRunning( );
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tStopwatchAppWindowCore_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# ePaintEvent
 * entry port: ePaintEvent
 * signature:  sTWPaintEvent
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# ePaintEvent_paint
 * name:         ePaintEvent_paint
 * global_name:  tStopwatchAppWindowCore_ePaintEvent_paint
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
ePaintEvent_paint(CELLIDX idx)
{
	CELLCB	*p_cellcb = GET_CELLCB(idx);

	int w = 960, h = 640;
	TWRect r;

	TWSetRect(&r, 0, 0, w, h);
	cDC_fillRect(TWMakeColor(192, 192, 192), &r);
}

/* #[<ENTRY_PORT>]# eStartStopButtonActivated
 * entry port: eStartStopButtonActivated
 * signature:  sAction
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eStartStopButtonActivated_activated
 * name:         eStartStopButtonActivated_activated
 * global_name:  tStopwatchAppWindowCore_eStartStopButtonActivated_activated
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eStartStopButtonActivated_activated(CELLIDX idx)
{
    CELLCB  *p_cellcb = GET_CELLCB(idx);
    if (cStopwatch_isRunning()) {
        cStopwatch_stop();
    } else {
        cStopwatch_start();
    }
}

/* #[<ENTRY_PORT>]# eResetLapButtonActivated
 * entry port: eResetLapButtonActivated
 * signature:  sAction
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eResetLapButtonActivated_activated
 * name:         eResetLapButtonActivated_activated
 * global_name:  tStopwatchAppWindowCore_eResetLapButtonActivated_activated
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eResetLapButtonActivated_activated(CELLIDX idx)
{
    CELLCB  *p_cellcb = GET_CELLCB(idx);

    cStopwatch_stop();
    cStopwatch_reset();
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
