/*
 * This file was automatically generated by tecsgen.
 * Move and rename like below before editing,
 *   gen/tTWValueSourceCallbackSplitter_template.c => src/tTWValueSourceCallbackSplitter.c
 * to avoid to be overwritten by tecsgen.
 */
/* #[<PREAMBLE>]#
 * Don't edit the comments between #[<...>]# and #[</...>]#
 * These comment are used by tecsmerege when merging.
 *
 * call port function #_TCPF_#
 * call port: cCallback signature: sTWValueSourceCallback context:task optional:true
 *   bool_t     is_cCallback_joined(int subscript)        check if joined
 *   void           cCallback_changing( subscript );
 *   void           cCallback_changed( subscript );
 *       subscript:  0...(NCP_cCallback-1)
 *
 * #[</PREAMBLE>]# */

/* Put prototype declaration and/or variale definition here #_PAC_# */
#include "tTWValueSourceCallbackSplitter_tecsgen.h"

#ifndef E_OK
#define	E_OK	0		/* success */
#define	E_ID	(-18)	/* illegal ID */
#endif

/* entry port function #_TEPF_# */
/* #[<ENTRY_PORT>]# eCallback
 * entry port: eCallback
 * signature:  sTWValueSourceCallback
 * context:    task
 * #[</ENTRY_PORT>]# */

/* #[<ENTRY_FUNC>]# eCallback_changing
 * name:         eCallback_changing
 * global_name:  tTWValueSourceCallbackSplitter_eCallback_changing
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eCallback_changing(CELLIDX idx)
{
	CELLCB *p_cellcb = GET_CELLCB(idx);

	for (int_t i = 0; i < NCP_cCallback; ++i) {
		cCallback_changing(i);
	}
}

/* #[<ENTRY_FUNC>]# eCallback_changed
 * name:         eCallback_changed
 * global_name:  tTWValueSourceCallbackSplitter_eCallback_changed
 * oneway:       false
 * #[</ENTRY_FUNC>]# */
void
eCallback_changed(CELLIDX idx)
{
	CELLCB *p_cellcb = GET_CELLCB(idx);

	for (int_t i = 0; i < NCP_cCallback; ++i) {
		cCallback_changed(i);
	}
}

/* #[<POSTAMBLE>]#
 *   Put non-entry functions below.
 * #[</POSTAMBLE>]#*/
